const thisWeek = new Discord.MessageEmbed()
.setTitle("This is your title, it can hold 256 characters")
.setAuthor("Author Name", "https://i.imgur.com/lm8s41J.png")
.setColor(0x00AE86)
.setDescription("This is the main body of text, it can hold 2048 characters.")
.setFooter("This is the footer text, it can hold 2048 characters", "http://i.imgur.com/w1vhFSR.png")
.setImage("https://www.no-cookie.com/w/images/f/fa/Sauvetage_de_l%27Avant-garde_-_fantassin_Tate-carte.jpg")
.setThumbnail("http://i.imgur.com/p2qNFag.png")
.setTimestamp()
.setURL("https://discord.js.org/#/docs/main/v12/class/MessageEmbed")
.addFields({ name: "This is a field title, it can hold 256 characters",
    value: "This is a field value, it can hold 1024 characters."})
.addFields({ name: "Inline Field", value: "They can also be inline.", inline: true })
.addFields({ name: '\u200b', value: '\u200b' })
.addFields({ name: "Inline Field 3", value: "You can have a maximum of 25 fields.", inline: true})
message.author.send(thisWeek)
